name:                lambda-chat-server
version:             0.1.0.0
github:              "yes91/lambda-chat-server"
license:             BSD3
author:              "Kieran Blazier"
maintainer:          "kieranblazier@gmail.com"
copyright:           "2019 Kieran Blazier"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/yes91/lambda-chat-server#readme>

dependencies:
- base >= 4.7 && < 5
- network
- containers
- mtl
- bimap
- random
- stm
- pipes
- pipes-binary
- pipes-network
- pipes-parse
- lambda-chat-protocol

library:
  source-dirs: src
  default-extensions:
    - FlexibleContexts
    - RecordWildCards

executables:
  lambda-chat-server:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lambda-chat-server

tests:
  lambda-chat-server-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lambda-chat-server
